# docker-compose.yaml
# 同样遵循严格的缩进
version: '3.1'

# services 定义容器列表
services:
    database:
        image: postgres
        ports:
            - 5432:5432
        environment:
            POSTGRES_PASSWORD: "asdfweiiweo"
    datastore:
        image: mongo
        ports:
            - 27017:27017
    consignment-cli:
        build: ./consignment-cli
        environment:
            MICRO_REGISTRY: "mdns"
    user-cli:
        build: ./user-cli
        environment:
            MICRO_REGISTRY: "mdns"

    consignment-service:
        build: ./consignment-service
        ports:
            - 50051:50051
        environment:
            MICRO_ADRESS: ":50051"
            MICRO_REGISTRY: "mdns"
            DB_HOST: "datastore:27017"

    vessel-service:
        build: ./vessel-service
        ports:
            - 50052:50051
        environment:
            MICRO_ADRESS: ":50051"
            MICRO_REGISTRY: "mdns"
            DB_HOST: "datastore:27017"
    user-service:
        build: ./user-service
        ports:
            - 50053:50051
        environment:
            POSTGRES_HOST: "database"
            POSTGRES_USER: "postgres"
            POSTGRES_NAME: "postgres"
            POSTGRES_PASSWORD: "asdfweiiweo"
